<?php

declare(strict_types=1);

namespace App\Presenters;

use Nette;


final class FilterPresenter extends Nette\Application\UI\Presenter
{
    public function __construct()
    {

    }
    protected function startup()
    {
        parent::startup(); // TODO: Change the autogenerated stub
        $this->template->teplota = [[2,2,2],[2,2,2],[2,2,2]];
    }

}
