<?php

declare(strict_types=1);

namespace App\Presenters;

use Nette;


final class InfoPresenter extends Nette\Application\UI\Presenter
{
    public function __construct()
    {

    }
    protected function startup()
    {
        parent::startup(); // TODO: Change the autogenerated stub
    }

}
