<?php

declare(strict_types=1);

namespace App\Presenters;

use Nette;


final class PlacePresenter extends Nette\Application\UI\Presenter
{
    public function __construct()
    {
    }
    public function startup()
    {
        parent::startup(); // TODO: Change the autogenerated stub
        $this->template->doma = [[0,0,0],[0,0,0]];
    }
}
